// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioApi.Data;

#nullable disable

namespace PortfolioApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260406135103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolio")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioApi.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contacts", "portfolio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Wausau",
                            Comment = "Hello Jim.",
                            Company = "Test",
                            Email = "hello@gmail.com",
                            FirstName = "Jim",
                            LastName = "Moua",
                            PhoneNumber = "715-517-3421",
                            State = "WI",
                            Zip = "54401"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects", "portfolio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "For my Data Concepts class, I used SQL to create a database around my hobby of Gunpla. Initially, I made a data dictionary and crow’s foot diagram to establish its structure. Then I went into SQL Server to create the database and the entities/tables within, along with adding in the necessary data. This project was a culmination of everything I learned in Data Concepts A-C regarding database design and entity relationships.",
                            Image = "/images/project1_DataConcepts.png",
                            Link = "",
                            Title = "Create Your Own Database",
                            Type = "Data Concepts"
                        },
                        new
                        {
                            Id = 2,
                            Description = "For College 101, I created a visual of what I thought were the most important qualities to succeed. During the course, I was to read an online book, with each chapter detailing a specific quality needed to succeed. Out of the total eight, I chose ‘Emotional Intelligence’, ‘Lifelong Learning’, and ‘Greater Personal Responsibility’ as the most vital. These three qualities would be the most important in achieving my personal form of success.",
                            Image = "/images/project2_College101.png",
                            Link = "",
                            Title = "Success PAT",
                            Type = "Other"
                        },
                        new
                        {
                            Id = 3,
                            Description = "For my Web Design class, I was to finish this website by handling its interactivity and animation. Using HTML and CSS, I gave each of the headings (DOWNLOAD, SCREENSHOTS, etc.) visual changes and inserted three animals that could move on the screen. This was probably the most difficult assignment for me as I had to use tools like F12 to fix some of the issues with the animals not loading in correctly.",
                            Image = "/images/project3_WebDesign.png",
                            Link = "",
                            Title = "Pixel Arcade",
                            Type = "Web Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
